FROM mcr.microsoft.com/dotnet/aspnet:7.0

RUN apt-get update && apt-get install -y \
    procps  \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y curl

RUN apt-get install sudo

RUN curl https://purevpn-dialer-assets.s3.amazonaws.com/cross-platform/linux-cli/production/cli-install.sh | bash

RUN echo "export PATH=$PATH:/opt/purevpn-cli/bin" >> ~/.bashrc && . ~/.bashrc

RUN purevpn-cli -V | bash
RUN purevpn-cli -l | bash

