FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN apt-get update && \
    apt-get install -y \
        wget \
        apt-transport-https \
        procps \
    # Установка procdump
    && wget https://packages.microsoft.com/config/debian/$(cat /etc/debian_version | cut -d'.' -f1)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y procdump \
    # Очистка кеша
    && rm -rf /var/lib/apt/lists/*
