#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi
if [ "$1" = "purge" ]; then
    rm -rf /var/lib/hsm-linux-probe /var/log/hsm-linux-probe
fi
exit 0
