name: DockerDepsCheck
on:
  push:
    branches: [master, develop]

  workflow_dispatch:
    inputs:
      isPreRelease:
        description: 'PreRelease'
        type: boolean
        required: true
        default: false
env:
  OUTPUT_FOLDER: ${{ github.workspace }}/BuildOutput

  SOLUTION_PATH: src/server/HSMServer/HSMServer.sln
  SERVER_PATH: src/module/HSMPingModule/HSMPingModule.csproj

  DOCKER_DOCKERHUB_ORG: pawgyrocopter
  DOCKER_DEPS_REPOS: hierarchical_sensor_monitoring_deps
  DOCKER_DEPS_TAG: latest
  DOCKER_MAIN_REPOS: hsmpingmodule

jobs:
  publish-docker-deps:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: DockerHub
    env:
      DockerfilePath: .github/docker/dockerfile_deps_pingmodule
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Build and push docker deps
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ${{ env.DockerfilePath }}
          tags: ${{ env.DOCKER_DOCKERHUB_ORG }}/${{ env.DOCKER_DEPS_REPOS }}:${{ env.DOCKER_DEPS_TAG }}
